import './style.css';
import {SERVICES, EXPENSES, today, metrics, validRecord, monthlyGoal} from './model.js';
const KEY='delivery-income-v1';
const yen=v=>v===null?'—':`¥${Math.round(v).toLocaleString('ja-JP')}`;
const app=document.querySelector('#app');
let records=[], page='dashboard', period='month', editing=null, notice='', storageBlocked=false;
try { const raw=localStorage.getItem(KEY); if(raw) { const parsed=JSON.parse(raw); if(!Array.isArray(parsed)||!parsed.every(validRecord)||new Set(parsed.map(r=>r.date)).size!==parsed.length) throw Error(); records=parsed; } } catch { storageBlocked=true; notice='保存データを読み込めませんでした。データ保護のため保存を停止しています。ブラウザーの保存設定を確認してください。'; }
function persist(next) { if(storageBlocked) { alert('保存データを読み込めないため保存を停止しています。ブラウザーの保存設定を確認してください。'); return false; } try { localStorage.setItem(KEY,JSON.stringify(next)); records=next; return true; } catch { alert('保存できませんでした。ブラウザーの空き容量や保存設定を確認してください。入力内容はこの画面に残っています。'); return false; } }
function dateLabel(date) {return new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${date}T12:00:00`));}
function summary(m) {return `<div class="summary"><div><span>売上</span><strong>${yen(m.revenue)}</strong></div><div><span>経費</span><strong>${yen(m.expense)}</strong></div><div class="profit"><span>利益</span><strong class="${m.profit<0?'negative':''}">${yen(m.profit)}</strong></div></div>`;}
function goalCard() {
 const g=monthlyGoal(records);
 return `<section class="card monthly-goal" aria-label="月間売上目標"><div class="section-heading"><h2>今月の売上目標</h2><span>70万円</span></div><p class="goal-remaining">${g.remaining ? `売上70万円まであと <strong>${yen(g.remaining)}</strong>` : '<strong>売上70万円の目標達成！</strong>'}</p><div class="goal-progress" role="progressbar" aria-label="月間売上目標の達成率" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${g.progress.toFixed(1)}"><span style="width:${g.progress}%"></span></div><div class="goal-status"><span>今月の売上 ${yen(g.revenue)}</span><span>${Math.floor(g.progress)}% 達成</span></div><p class="goal-daily">今月あと <strong>${g.daysLeft}日</strong> → 1日 <strong>${yen(g.dailyRequired)}</strong> 必要</p><p class="help">今日を含む残り日数で計算・必要額は1円単位で切り上げ</p></section>`;
}
function dashboard() {
 const selected=records.filter(r=>period==='today'?r.date===today():r.date.slice(0,7)===today().slice(0,7)), m=metrics(selected);
 return `<div class="heading"><div><p class="eyebrow">YOUR DELIVERY NOTE</p><h1>毎日の頑張りを、<br>ひと目で。</h1></div><span class="date-chip">${dateLabel(today())}</span></div><div class="period"><button data-period="today" class="${period==='today'?'active':''}">今日</button><button data-period="month" class="${period==='month'?'active':''}">今月</button></div><section class="hero"><div class="hero-top"><span>${period==='today'?'今日':'今月'}の利益</span><span>売上 − 経費</span></div><div class="hero-value">${yen(m.profit)}</div><div class="hero-bottom"><div>売上<strong>${yen(m.revenue)}</strong></div><div>経費<strong>${yen(m.expense)}</strong></div></div></section>${goalCard()}<div class="stat-grid"><section class="card"><span class="muted">時給</span><strong>${yen(m.hourly)}<small> / 時間</small></strong><p>稼働 ${Number(m.hours.toFixed(2))} 時間</p></section><section class="card"><span class="muted">1件あたりの売上</span><strong>${yen(m.perOrder)}<small> / 件</small></strong><p>配達 ${m.count} 件</p></section></div><section class="card"><div class="section-heading"><h2>サービス別の売上</h2><span>${period==='today'?'今日':'今月'}</span></div>${SERVICES.map((s,i)=>`<div class="service-row"><span class="service-dot service-${i}"></span><span>${s}</span><strong>${yen(m.sales[i])}</strong></div><div class="bar"><span class="service-${i}" style="width:${m.revenue?m.sales[i]/m.revenue*100:0}%"></span></div>`).join('')}</section><div class="section-heading"><h2>最近の記録</h2><button class="text-button" data-page="history">すべて見る →</button></div>${recordList([...records].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3))}<button class="primary wide" data-new>＋ 今日の記録をつける</button>`;
}
function recordList(list) { return list.length?list.map(r=>{const m=metrics([r]);return `<button class="record" data-edit="${r.id}"><div><strong>${dateLabel(r.date)}</strong><span>${r.hours} 時間 · ${r.count} 件</span></div><div><small>利益</small><strong class="${m.profit<0?'negative':''}">${yen(m.profit)} <span class="chevron">›</span></strong></div></button>`;}).join(''):`<div class="empty"><span class="empty-icon">＋</span><h3>ここから、記録をはじめよう</h3><p>売上や経費を入力すると<br>収支が自動でまとまります。</p></div>`; }
function history() { return `<p class="eyebrow">YOUR RECORDS</p><h1>過去の記録</h1><p class="muted">記録をタップすると編集・削除できます。</p><label class="filter">表示する月<input type="month" id="history-month" value="${today().slice(0,7)}"></label><div id="history-list">${historyList(today().slice(0,7))}</div>`; }
function historyList(month) {const list=records.filter(r=>r.date.slice(0,7)===month).sort((a,b)=>b.date.localeCompare(a.date));return summary(metrics(list))+`<p class="muted">${list.length} 日分の記録</p>`+recordList(list);}
function form() {
 const r=records.find(r=>r.id===editing)||{date:today(),sales:[0,0,0,0],expenses:[0,0,0,0,0],hours:0,count:0};
 const moneyFields=(names,values,type)=>names.map((name,i)=>`<label class="field-row"><span>${name}</span><div class="input-unit"><span>¥</span><input aria-label="${type==='sales'?'売上':'経費'} ${name}" name="${type}-${i}" type="number" inputmode="numeric" min="0" max="999999999" step="1" placeholder="0" value="${values[i]||''}"></div></label>`).join('');
 return `<p class="eyebrow">DAILY NOTE</p><h1>${editing?'記録を編集':'今日の記録'}</h1><p class="muted">空欄は 0 として計算します。1日につき1つの記録です。</p><form id="entry"><section class="card"><label class="date-field">記録する日付<input name="date" aria-label="記録する日付" type="date" required value="${r.date}"></label></section><section class="card"><h2><span class="step">01</span>サービス別の売上</h2>${moneyFields(SERVICES,r.sales,'sales')}</section><section class="card"><h2><span class="step">02</span>稼働と配達</h2><label class="field-row"><span>稼働時間</span><div class="input-unit"><input name="hours" aria-label="稼働時間" type="number" inputmode="decimal" min="0" max="24" step="0.01" placeholder="0" value="${r.hours||''}"><span>時間</span></div></label><p class="help">例：3時間30分 → 3.5 時間</p><label class="field-row"><span>配達件数</span><div class="input-unit"><input name="count" aria-label="配達件数" type="number" inputmode="numeric" min="0" max="9999" step="1" placeholder="0" value="${r.count||''}"><span>件</span></div></label></section><section class="card"><h2><span class="step">03</span>経費</h2>${moneyFields(EXPENSES,r.expenses,'expenses')}</section><section class="card calculation"><h2>この日の収支</h2><div id="live-summary"></div><p class="help">時間・件数が 0 の場合、時給・1件あたりは「—」と表示します。</p></section><p id="form-error" role="alert" class="negative"></p><button class="primary wide" type="submit">${editing?'変更を保存する':'記録を保存する'}</button><button class="secondary wide" type="button" data-page="dashboard">キャンセル</button>${editing?'<button type="button" class="delete wide" id="delete">この記録を削除する</button>':''}</form>`;
}
function render() {
 app.innerHTML=`<header><a href="#" class="brand" data-page="dashboard"><span class="brand-icon">↗</span>デリログ<span class="brand-sub">DELIVERY LOG</span></a><span class="personal">自分のための収支ノート</span></header><main>${notice?`<p class="notice" role="status">${notice}</p>`:''}${page==='dashboard'?dashboard():page==='history'?history():form()}<footer>このブラウザーに自動保存されます。<br>データは端末・ブラウザー間で共有されません。<br>閲覧データの削除やシークレットモードの終了で記録が失われます。</footer></main><nav aria-label="メインナビゲーション"><button data-page="dashboard" class="${page==='dashboard'?'selected':''}"><span aria-hidden="true">▦</span>ホーム</button><button data-new class="${page==='entry'?'selected':''}"><span aria-hidden="true">＋</span>記録する</button><button data-page="history" class="${page==='history'?'selected':''}"><span aria-hidden="true">☷</span>履歴</button></nav>`;
 app.querySelectorAll('[data-page]').forEach(b=>b.onclick=e=>{e.preventDefault();page=b.dataset.page;notice='';render();window.scrollTo(0,0);});
 app.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>{editing=records.find(r=>r.date===today())?.id||null;page='entry';notice='';render();window.scrollTo(0,0);});
 app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;page='entry';notice='';render();window.scrollTo(0,0);});
 app.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;render();});
 const month=app.querySelector('#history-month'); if(month) month.onchange=()=>{app.querySelector('#history-list').innerHTML=historyList(month.value);app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;page='entry';render();window.scrollTo(0,0);});};
 const f=app.querySelector('#entry'); if(f) {
 const read=()=>({id:editing||crypto.randomUUID(),date:f.elements.date.value,sales:SERVICES.map((_,i)=>Number(f.elements[`sales-${i}`].value)),expenses:EXPENSES.map((_,i)=>Number(f.elements[`expenses-${i}`].value)),hours:Number(f.elements.hours.value),count:Number(f.elements.count.value)});
 const update=()=>{const m=metrics([read()]);app.querySelector('#live-summary').innerHTML=summary(m)+`<div class="live-rates"><span>時給 <strong>${yen(m.hourly)}</strong></span><span>1件あたり <strong>${yen(m.perOrder)}</strong></span></div>`;};f.oninput=update;update();
 f.onsubmit=e=>{e.preventDefault();const r=read();const error=app.querySelector('#form-error');if(!validRecord(r)){error.textContent='日付と入力値を確認してください。金額・件数は0以上の整数、稼働時間は0〜24時間で入力します。';return;}if(records.some(x=>x.date===r.date&&x.id!==r.id)){error.textContent='この日付の記録はすでにあります。履歴から該当日の記録を編集してください。';return;}if(persist([...records.filter(x=>x.id!==r.id),r])){page='dashboard';notice='記録を保存しました。';render();window.scrollTo(0,0);}};
 const del=app.querySelector('#delete');if(del) del.onclick=()=>{if(confirm('この日の記録を削除しますか？削除した記録は元に戻せません。')&&persist(records.filter(r=>r.id!==editing))){page='history';notice='記録を削除しました。';render();window.scrollTo(0,0);}};
 }
}
render();
